### PR TITLE
respect assets that have been ignored

### PR DESCRIPTION
**Pull request by stevenosloan**
@tdreyno here's a partial fix for #96 / https://github.com/middleman/middleman/issues/1789 -- I realized I'm not quite sure what the correct behavior for linked assets is though.

With this implementation -- ignored assets are never processed, so if they had linked assets they aren't linked. But since we're inserting linked assets after the ignore descriptors have run -- they don't get ignored. I feel like this is the "least surprising" option, but leaves me with two questions:
- should we process ignored assets for links
- should linked assets be ignorable (I'm not sure why you would do this, and it could cause issues as the link indicates a dependency)

look forward to your thoughts

### CODE REVIEW

**Comment by tdreyno** [comment]
I think we should process ignored assets for links. It is possible to proxy to an ignored asset.

I think they should be ignorable, if possible. It might blow up in people's faces, but atleast its predictable. Some sprockets gems link a ton of shit they don't need (fonts, icons, etc)

**Comment by stevenosloan** [comment]
Cool, glad I asked :)

Is the best way to run the sprockets assets through the ignore descriptors to call `app.extensions[:sitemap_ignore].manipulate_resource_list` with the resources from middleman-sprocket's `manipulate_resource_list`?

**Comment by stevenosloan** [comment]
Looks like I've got some work to do for MM 4.0, but does this match what you were thinking? https://github.com/middleman/middleman-sprockets/pull/97/commits/debae5700d739727efff9ea6811a3d3397770e7e#diff-7cd0aea0abb64cf9966fafa7c916f2b7

**Comment by tdreyno** [comment]
What is `base_resource?`

**Comment by stevenosloan** [comment]
That's a great question -- was left in since the initial v4 lift. My assumption is it was put in place to make sure the extension was only acting on "original" `Middleman::Sitemap::Resource` objects -- that way it wouldn't re-create `SprocketsResource`s, but I guess that means it wouldn't act on `ProxyResource`s (or others) either.

**Comment by tdreyno** [comment]
I think it makes sense to try and support any resource type (and except our Sprockets resources directly?). The sitemap is kind of duck-type-y.

**Comment by tdreyno** [comment]
Also, merge away if you're happy

**Comment by stevenosloan** [comment]
"delete method" refactoring is my favorite :)

Will try this for now then can come up w/ a good test case if anyone runs into trouble.

**Pull request merged**
