### PR TITLE
Give sprockets access to middleman helpers

### PR DESCRIPTION
**Pull request by stevenosloan**
Related to https://github.com/middleman/middleman/issues/1801

Hiding this behind a config because the edge cases could be fairly hairy. This also special cases `current_resource` as non-implemented for now.

To turn it on, in config.rb

```ruby
set :sprockets_expose_middleman_helpers, true
```

@johanhalse if you could give this a shot that'd be great.

### CODE REVIEW

**Comment by johanhalse** [comment]
@stevenosloan yes! that does the trick and I can re-use the same code that worked for Middleman 3.

**Comment by tdreyno** [comment]
@stevenosloan Can you add this as an option on the extension itself (in addition to the root `set` variable)? Someday, I think it'll make since to stop auto-activating this and just do a normal `activate :sprockets`

**Comment by stevenosloan** [comment]
@tdreyno Yeah definitely -- and I've been thinking the same re: auto-activating. Configuring stuff this way is pretty clunky. 

For now do you think it's better to suggest configuring like:
```ruby
extensions[:sprockets].options[:expose_middleman_helpers] = true
```

Or expose a configuration method to `config.rb`?

**Comment by stevenosloan** [comment]
@tdreyno I'll rebase before merging in, but does this look good to you for configuration? https://github.com/stevenosloan/middleman-sprockets/commit/c05dfb0af00f13d13fe88381d3175734f5a36db4

**Comment by tdreyno** [comment]
Well, since technically Sprockets hasn't been released for v4, we could switch to the manual activation now.

**Comment by tdreyno** [comment]
Everything else looks good

**Comment by stevenosloan** [comment]
Cool, yeah -- there's enough other changes (and it is a major version bump) that requiring manual activation feels like a pretty low bar. Will get that change made and merge things in.

**Pull request merged**
