### PR TITLE
4.0.0.rc.2

### PR DESCRIPTION
**Pull request by stevenosloan**
@tdreyno https://github.com/middleman/middleman-sprockets/issues/103 is turning out to be pretty hairy and is going to take a while to figure out. You mind releasing a rc.2 in the meantime?

### CODE REVIEW

**Comment by tdreyno** [comment]
Let me add you as a contributor. What's your ruby gems account email address?

`rake release` to publish after you haver permissions

**Comment by stevenosloan** [comment]
👍 it's stevenosloan@gmail.com

**Comment by tdreyno** [comment]
Done. You're the man now, dog.

**Comment by stevenosloan** [comment]
Sweet thanks, hadn't used those bundler rake tasks before -- they're pretty neat.

**Pull request merged**
